apiVersion: v1
kind: Secret
metadata:
  name: xiv-raid-reminder-config
stringData:
  config.json: |
    {
      "spreadsheet_api_key": {{ .Values.spreadsheetApiKey | default "" | quote }},
      "spreadsheet_id":      {{ .Values.spreadsheetId     | default "" | quote }},
      "discord_webhook_url": {{ .Values.discordWebhookUrl | default "" | quote }}
    }
