---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xiv-raid-reminder-{{ .Release.Name }}
spec:
  schedule: {{ .Values.remindTime | default "0 0 * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: xiv-raid-reminder
            image: "{{ .Values.jobContainer.image.name }}:{{ .Values.jobContainer.image.tag | default .Chart.AppVersion }}"
            resources:
              requests:
                cpu: {{ .Values.jobContainer.requests.cpu | default "200m" }}
                memory: {{ .Values.jobContainer.requests.memory | default "128Mi" }}
              limits:
                cpu: {{ .Values.jobContainer.limits.cpu | default "200m" }}
                memory: {{ .Values.jobContainer.limits.memory | default "128Mi" }}
            volumeMounts:
            - name: config
              mountPath: /config.json
              readOnly: true
              subPath: config.json
          volumes:
          - name: config
            secret:
              secretName: xiv-raid-reminder-config-{{ .Release.Name }}
          restartPolicy: OnFailure
