---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xiv-raid-reminder-{{ .Release.Name }}
spec:
  schedule: {{ .Values.remindTime | default "0 0 * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: xiv-raid-reminder
            image: gcr.io/neigepluie/xiv-raid-reminder:{{ .Values.jobContainerTag | default "latest" }}
            resources:
              requests:
                memory: "128Mi"
                cpu: "200m"
              limits:
                memory: "128Mi"
                cpu: "200m"
            volumeMounts:
            - name: config
              mountPath: /config.json
              readOnly: true
              subPath: config.json
          volumes:
          - name: config
            secret:
              secretName: xiv-raid-reminder-config-{{ .Release.Name }}
          restartPolicy: OnFailure
